services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      - MEILI_MASTER_KEY
    ports:
      - 7700:7700
    volumes:
      - ./data/meili:/meili_data

  elasticsearch:
    image: elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD
      - KIBANA_PASSWORD
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/elastic/certs:/usr/share/elasticsearch/config/certs

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - 8108:8108
    volumes:
      - ./data/typesense:/data
    command: '--data-dir /data --api-key=$TYPESENSE_API_KEY --enable-cors'
